use_frameworks!

platform :ios, '11.0'

target 'CocoaLumberjackTool_Example' do
  pod 'CocoaLumberjackTool', :path => '../'

  target 'CocoaLumberjackTool_Tests' do
    inherit! :search_paths

    
  end
end
